#!/bin/bash

/usr/bin/setxkbmap be -option 'caps:ctrl_modifier' &
/usr/bin/xcape -e 'Caps_Lock=Escape' -t 500 &

pkill sxhkd
/usr/bin/sxhkd &

wmname LG3D &

# Launch general apps (NOTE: order matters) {{{
xrdb $HOME/.Xresources
# }}}

# Main bspwm config {{{
bspc monitor 'Virtual1' -d I II III IV V VI

xsetroot -cursor_name left_ptr

bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.50
bspc config top_padding          45
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config ignore_ewmh_focus    false
# }}}

# Application rules {{{
# }}}

# Border color {{{
bspc config normal_border_color $color0
bspc config focused_border_color $color1
bspc config active_border_color $color1
bspc config presel_feedback_color $color1
# }}}

